name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main  # O cambia a "master" si esa es tu rama principal

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Aquí especificamos Node.js 18, que es compatible con Angular 18

    - name: Install dependencies
      run: npm install

    - name: Build the Angular app
      run: npm run build --prod -- --base-href "https://arieldavid-oss.github.io/calculadora-de-inversiones/"

    - name: Deploy to GitHub Pages
      run: npx angular-cli-ghpages --dir=dist/calculadora-de-inversiones
