# This is a basic workflow to help you get started with Actions

name: AngularCalculadora

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "18"
        #instalar dependencias
      - name: Install deps
        run: npm i
      - name: Build app bundle
        run: npm run build:prod
      - name: Deploy to peges
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/essential-practice
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
        
